version: '3.5'

services: 
    nginx:
        build: 
            context: ./docker/nginx
            dockerfile: nginx.Dockerfile
        networks: 
            - frontend
        ports: 
            - 8080:80
        links:
            - php-fpm
        volumes: 
            - ./src:/var/www/app
        container_name: nginx

    php-fpm:
        build: 
            context: ./docker/php-fpm
            dockerfile: php-fpm.Dockerfile
        networks: 
            - frontend
            - backend
        links:
            - mariadb
        volumes: 
            - ./src:/var/www/app
        container_name: php-fpm

    mariadb:
        build: 
            context: ./docker/mariadb
            dockerfile: mariadb.Dockerfile
        networks: 
            - backend
        ports: 
            - 13306:3306
        volumes: 
            - ./data:/var/lib/mysql
        container_name: mariadb

networks: 
    frontend:
        driver: bridge

    backend:
        driver: bridge
